version: '3'
services:
  mail:
    image: namshi/smtp
    restart: always
    container_name: mail
    read_only: true
    build:
      context: ./
      dockerfile: mail-Dockerfile
    volumes:
      - "/opt/misp-web/mail/etc/:/etc/:rw"
      - "/opt/misp-web/mail/var/:/var/:rw"
    healthcheck:
      test: ["CMD", "nc", "-v", "-w1", "127.0.0.1", "25"]
      timeout: 10s
      retries: 5

  redis:
    image: redis:5.0.6
    container_name: redis
    restart: always
    read_only: true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
    volumes:
      - "/opt/misp-web/redis/data:/data:rw"


  db:
    image: mysql:8.0.19
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    read_only: true
    environment:
      - "MYSQL_USER=${MYSQLUSER}"
      - "MYSQL_PASSWORD=${MYSQLPASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQLROOTPASSWORD}"
      - "MYSQL_DATABASE=${MYSQLDATABASE}"
    volumes:
      - "/opt/misp-web/mysql/:/var/lib/mysql:rw"
      - "/opt/misp-web/mysql_log/:/var/log:rw"
      - "/opt/misp-web/mysql_etc/:/etc:rw"
      - "/opt/misp-web/mysql_tmp:/tmp:rw"
      - "/opt/misp-web/mysql_var/run/mysqld:/var/run/mysqld:rw"
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-ppassword", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  misp:
    image: coolacid/misp-docker:core-latest
    restart: always
    read_only: false
    container_name: misp-web
    depends_on:
      - redis
      - db
    ports:
      - "${SERVER_NAME}:80:80"
      - "${SERVER_NAME}:443:443"
    volumes:
      - "/opt/misp-web/server-configs/:/var/www/MISP/app/Config/"
      - "/opt/misp-web/logs/:/var/www/MISP/app/tmp/logs/"
      - "/opt/misp-web/files/:/var/www/MISP/app/files"
      - "/opt/misp-web/ssl/:/etc/nginx/certs"
      - "/opt/misp-web/tmp/:/tmp/"
      - "/opt/misp-web/var/tmp/:/var/tmp/"
      - "/opt/misp-web/usr/tmp/:/usr/tmp"
    environment:
      - "HOSTNAME=https://${SERVER_NAME}"
      - "REDIS_FQDN=redis"
      - "INIT=true"
      - "CRON_USER_ID=1"
    healthcheck:
      test: ["CMD", "nc", "-v", "-w1", "127.0.0.1", "443"]
      timeout: 10s
      retries: 5

  misp-modules:
    image: coolacid/misp-docker:modules-latest
    restart: always
    read_only: true
    build:
      context: ./
      dockerfile: misp-modules-Dockerfile
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis
      - db
    healthcheck:
      test: ["CMD", "nc", "-v", "-w1", "127.0.0.1", "6666"]
      timeout: 10s
      retries: 5


volumes:
    mysql_data:
