version: '3'
services:
  mail:
    image: namshi/smtp

  redis:
    image: redis:5.0.6

  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_USER=${MYSQLUSER}"
      - "MYSQL_PASSWORD=${MYSQLPASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQLROOTPASSWORD}"
      - "MYSQL_DATABASE=${MYSQLDATABASE}"
    volumes:
      - /opt/misp-web/mysql/:/var/lib/mysql
    cap_add:
      - SYS_NICE

  misp:
    image: coolacid/misp-docker:core-latest
    depends_on:
      - redis
      - db
    ports:
      - "${SERVER_NAME}:80:80"
      - "${SERVER_NAME}:443:443"
    volumes:
      - "/opt/misp-web/server-configs/:/var/www/MISP/app/Config/"
      - "/opt/misp-web/logs/:/var/www/MISP/app/tmp/logs/"
      - "/opt/misp-web/files/:/var/www/MISP/app/files"
      - "/opt/misp-web/ssl/:/etc/nginx/certs"
    environment:
      - "HOSTNAME=https://${SERVER_NAME}"
      - "REDIS_FQDN=redis"
      - "INIT=true"
      - "CRON_USER_ID=1"
  misp-modules:
    image: coolacid/misp-docker:modules-latest
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis
      - db

volumes:
    mysql_data:
